### ISSUE TITLE
Helm Chart Should Support Accessing Secrets as Files

### ISSUE THREAD

**Issue by conallob** [cloudprober/helm-charts#42]
I'm trying to follow the https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod pattern to mount kubernetes secrets (e.g TLS CA, keys, etc) as a file within my cloudprober pods.

After experimenting with numerous permutations, I realised the problem was with the helm chart parameters itself.

e.g If I want to configure mounting of this secret:

```
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
[...]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
```

However, looking at https://github.com/cloudprober/helm-charts/blob/main/cloudprober/templates/deployment.yaml#L62 , it appears to only be possible configure configMap mounts, with 4 config options `name`, `mountPath`, `subPath` and `ReadOnly`

https://github.com/cloudprober/helm-charts/blob/main/cloudprober/templates/deployment.yaml#L38 under `extraConfigmapMounts` will ensure every mount is always a `configMap`, and I can never define a volume using `secretName`

Could we add a second range under https://github.com/cloudprober/helm-charts/blob/main/cloudprober/templates/deployment.yaml#L62 to allow additional VolumeMounts of non configMaps please?
